version: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes
file_exists_behavior: OVERWRITE
# 파일 및 디렉토리에 관련된 설정
permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu

# Deploy 전후에 실행할 스크립트 또는 명령에 관련된 설정
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
